import random,gzip,os
random.seed(42)
B=os.path.dirname(os.path.abspath(__file__))
D16=os.path.join(B,'16S_sequences')
DIT=os.path.join(B,'ITS_sequences')
os.makedirs(D16,exist_ok=True)
os.makedirs(DIT,exist_ok=True)
V4={'Bacteroides_fragilis':'TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGAAACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCGGTGGCGAAAGCGGCTCTCTGGCCTGTAACTGACGCTGAGGCTCGAAAGCGT','Faecalibacterium_prausnitzii':'TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTTGAAACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAATACTGACGCTGAGGTGCGAAAGCGT','Lactobacillus_acidophilus':'TACGTAGGTGGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGAAACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGCTCTCTGGCCTGCAACTGACGCTGAGGCTCGAAAGCGT','Bifidobacterium_longum':'TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATTTGAAACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAATACTGACGCTGAGGTGCGAAAGCGT','Ruminococcus_gnavus':'TACGTAGGGGGCAAGCGTTGTCCGGATTTACTGGGCGTAAAGCGAGTGCAGGCGGCTCGATAAGTCCGATGTGAAATCCATGGGCTTAACCCATGAACTGCATCGGAAACTGTCGAGCTTGAGTACAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTAAAATGCGTAGATATATGGAGGAATACCAGTGGCGAAGGCGGCTCTCTGGGCTGTAACTGACGCTGAGGCTCGAAAGCGT','Akkermansia_muciniphila':'TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGCCTGTTAAGTCAGGGGTGAAATCCTGGAGCTTAACTCCAGAACTGCCTTTGATACTGGCAGGCTTGAGTATGGAAGAGGTAGGTGGAATTCCCGGTGTAGCGGTGAAATGCATAGATATCGGGAGGAACACCAGTGGCGAAGGCGACCTACTGGGCCTTTACTGACGCTGAGGCACGAAAGCGT','Prevotella_copri':'TACGTAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTCTTGTAAGACAGAGGTGAAATCCCTGGGCTCAACCCAGGAACTGCCTTTGTGACTGCAAGGCTAGAGTACGGCAGAGGGGGATGGAATTCCGCGTGTAGCAGTGAAATGCGTAGATATGCGGAGGAACACCGATGGCGAAGGCAATCCCCTGGGCCTGCACTGACGCTCATGCACGAAAGCGT','Clostridium_butyricum':'TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTCTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGAAACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGCTCTCTGGCCTGTAACTGACGCTGAGGCTCGAAAGCGT'}
ITS={'Aspergillus_niger':'CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTACCGAGTGCGGGTCCTCCGGGGCCCGAGCCCCCCGGGCGGTGTGCACGCCCCGGACCCCGAAACTTTGAAAGTTTTGGTTTCGCTGGCAGCCCAGCTTCGAGCGTATCGCACTTCTGAGTGTCAGAGCCCGTGACAGCAGAGCAGCCTAAAACTCGTAACGATGAATTTACAA','Candida_albicans':'CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTATTGAAAGTTTTGGTTTCGCTCGCAGAACCAGTACAAGCGCAAGTGTGAAAGTTGTTGCAGTTAAAAGCTCGTAGTTGGATTTCGGAGCGGATCGCTTGGCCTCCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGT','Saccharomyces_cerevisiae':'CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTATTGAGTGTATCGATAAGTAATGTGAATTGCAGAATCCCGTGAACATCGAGTCTTTGAACGCAAGTTGCGCCCGAGGCCATTAGGCCGAGGGCACGTCTGCCTGGGCGTCACGCATCGCGTCTCCGGCCCCGAAACCCAGTGCGGTAATTTACACAAATCAGTCAAACCCTTGT','Penicillium_chrysogenum':'CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTATTACCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTATGTTGCCTCGGCGGATCAGCCCGCTCCCCGTAAAAGGGCGGGTCCGCCCGCCTACCGTCCCTCGGGGCCCGAGCCCCCCGGGCGGTGTGCACGCCCCGGACCCCGAAACTTTGAAAGTTTTGGTTTCGCTGG','Fusarium_oxysporum':'CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTATTGCGAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTTTTTGAACGCAAGTTGCGCCCGAGGCCATTAGGCCGAGGGCACGTCTGCCTGGGCGTCACGCATCGCGTCTTCGGCCCCGAAACCCAGTGCGGTAATTTACACAAATCAGTCAAACCCTG','Trichoderma_harzianum':'CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTATTGAAAGTTTTGGTTTCGCTGGCAGCCCAGCTTCGAGCGTATCGCATTTCTGAGTGTCAGAGCCCGTGACAGCAGAGCAGCCTAAAACTCGTAACGATGAATTTACAACGATTCGGTTGCGCCCGAGGCCATTAGGCCGAGGGCACGTCTGCCTGGGCGTCACGCATCGCGT'}
def rc(s): return s.translate(str.maketrans('ACGTacgt','TGCAtgca'))[::-1]
def mut(s,r=0.003): return ''.join(random.choice('ACGT') if random.random()<r else c for c in s)
def qs(n,m=35):
    o=[]
    for i in range(n):
        q=max(18,min(40,m+random.randint(-5,4)-(max(0,int((i-n*0.8)*2)) if i>n*0.8 else 0)))
        o.append(chr(q+33))
    return ''.join(o)
def ws(d,sid,idx,seqs,comp,nr):
    ok,wt=list(comp.keys()),list(comp.values())
    r1,r2=[],[]
    for i in range(nr):
        o=random.choices(ok,weights=wt,k=1)[0]; t=seqs[o]
        f=mut(t[:240]); v=mut(rc(t)[:190])
        r1+=[f'@{sid}.{i+1} 1:N:0:ATCACG',f,'+',qs(len(f))]
        r2+=[f'@{sid}.{i+1} 2:N:0:ATCACG',v,'+',qs(len(v))]
    with gzip.open(f'{d}/{sid}_S{idx}_L001_R1_001.fastq.gz','wt') as f2: f2.write('\n'.join(r1)+'\n')
    with gzip.open(f'{d}/{sid}_S{idx}_L001_R2_001.fastq.gz','wt') as f2: f2.write('\n'.join(r2)+'\n')
    print(f'  wrote {sid}')
S16={'SRR001_healthy1':{'Faecalibacterium_prausnitzii':30,'Bacteroides_fragilis':22,'Akkermansia_muciniphila':18,'Bifidobacterium_longum':14,'Lactobacillus_acidophilus':10,'Prevotella_copri':6},'SRR002_healthy2':{'Faecalibacterium_prausnitzii':28,'Bacteroides_fragilis':24,'Akkermansia_muciniphila':16,'Bifidobacterium_longum':16,'Lactobacillus_acidophilus':10,'Ruminococcus_gnavus':6},'SRR003_healthy3':{'Faecalibacterium_prausnitzii':32,'Bacteroides_fragilis':20,'Akkermansia_muciniphila':18,'Bifidobacterium_longum':16,'Lactobacillus_acidophilus':8,'Ruminococcus_gnavus':6},'SRR004_healthy4':{'Faecalibacterium_prausnitzii':26,'Bacteroides_fragilis':26,'Akkermansia_muciniphila':16,'Bifidobacterium_longum':12,'Prevotella_copri':12,'Ruminococcus_gnavus':8},'SRR005_ibs1':{'Bacteroides_fragilis':36,'Clostridium_butyricum':26,'Ruminococcus_gnavus':20,'Prevotella_copri':10,'Faecalibacterium_prausnitzii':5,'Akkermansia_muciniphila':3},'SRR006_ibs2':{'Bacteroides_fragilis':38,'Clostridium_butyricum':22,'Ruminococcus_gnavus':18,'Prevotella_copri':14,'Faecalibacterium_prausnitzii':5,'Lactobacillus_acidophilus':3},'SRR007_ibs3':{'Bacteroides_fragilis':34,'Clostridium_butyricum':28,'Ruminococcus_gnavus':20,'Prevotella_copri':10,'Faecalibacterium_prausnitzii':5,'Bifidobacterium_longum':3},'SRR008_ibs4':{'Bacteroides_fragilis':40,'Clostridium_butyricum':22,'Ruminococcus_gnavus':16,'Prevotella_copri':14,'Faecalibacterium_prausnitzii':4,'Akkermansia_muciniphila':4},'SRR009_control1':{'Bacteroides_fragilis':22,'Faecalibacterium_prausnitzii':20,'Akkermansia_muciniphila':18,'Lactobacillus_acidophilus':16,'Bifidobacterium_longum':14,'Ruminococcus_gnavus':10},'SRR010_control2':{'Bacteroides_fragilis':20,'Faecalibacterium_prausnitzii':20,'Akkermansia_muciniphila':20,'Lactobacillus_acidophilus':16,'Bifidobacterium_longum':12,'Prevotella_copri':12},'SRR011_control3':{'Bacteroides_fragilis':18,'Faecalibacterium_prausnitzii':22,'Akkermansia_muciniphila':20,'Lactobacillus_acidophilus':14,'Bifidobacterium_longum':16,'Ruminococcus_gnavus':10},'SRR012_control4':{'Bacteroides_fragilis':24,'Faecalibacterium_prausnitzii':18,'Akkermansia_muciniphila':16,'Lactobacillus_acidophilus':18,'Bifidobacterium_longum':14,'Clostridium_butyricum':10}}
SIT={'ITS001_healthy1':{'Saccharomyces_cerevisiae':30,'Aspergillus_niger':22,'Trichoderma_harzianum':24,'Penicillium_chrysogenum':14,'Candida_albicans':6,'Fusarium_oxysporum':4},'ITS002_healthy2':{'Saccharomyces_cerevisiae':28,'Aspergillus_niger':24,'Trichoderma_harzianum':22,'Penicillium_chrysogenum':16,'Candida_albicans':6,'Fusarium_oxysporum':4},'ITS003_diseased1':{'Fusarium_oxysporum':40,'Candida_albicans':28,'Aspergillus_niger':16,'Penicillium_chrysogenum':10,'Saccharomyces_cerevisiae':4,'Trichoderma_harzianum':2},'ITS004_diseased2':{'Fusarium_oxysporum':44,'Candida_albicans':24,'Aspergillus_niger':14,'Penicillium_chrysogenum':10,'Saccharomyces_cerevisiae':5,'Trichoderma_harzianum':3},'ITS005_control1':{'Aspergillus_niger':26,'Saccharomyces_cerevisiae':22,'Trichoderma_harzianum':20,'Penicillium_chrysogenum':18,'Candida_albicans':8,'Fusarium_oxysporum':6},'ITS006_control2':{'Aspergillus_niger':24,'Saccharomyces_cerevisiae':24,'Trichoderma_harzianum':18,'Penicillium_chrysogenum':18,'Candida_albicans':10,'Fusarium_oxysporum':6},'ITS007_control3':{'Aspergillus_niger':22,'Saccharomyces_cerevisiae':26,'Trichoderma_harzianum':20,'Penicillium_chrysogenum':16,'Candida_albicans':10,'Fusarium_oxysporum':6},'ITS008_control4':{'Aspergillus_niger':28,'Saccharomyces_cerevisiae':20,'Trichoderma_harzianum':22,'Penicillium_chrysogenum':16,'Candida_albicans':8,'Fusarium_oxysporum':6}}
print('=== 16S ===')
for i,(s,c) in enumerate(S16.items(),1): ws(D16,s,i,V4,c,2000)
print('=== ITS ===')
for i,(s,c) in enumerate(SIT.items(),1): ws(DIT,s,i,ITS,c,1500)
m16='sample-id\tgroup\tage\tbmi\tsex\tdiet\tcollection-site\n#q2:types\tcategorical\tnumeric\tnumeric\tcategorical\tcategorical\tcategorical\nSRR001_healthy1\thealthy\t32\t22.4\tM\tWestern\tcolon\nSRR002_healthy2\thealthy\t28\t21.8\tF\tMediterranean\tcolon\nSRR003_healthy3\thealthy\t45\t23.1\tM\tMediterranean\tcolon\nSRR004_healthy4\thealthy\t38\t24.0\tF\tWestern\tcolon\nSRR005_ibs1\tibs\t34\t26.5\tF\tWestern\tcolon\nSRR006_ibs2\tibs\t41\t27.2\tM\tWestern\tcolon\nSRR007_ibs3\tibs\t29\t25.8\tF\tWestern\tcolon\nSRR008_ibs4\tibs\t52\t28.1\tM\tMediterranean\tcolon\nSRR009_control1\tcontrol\t36\t23.9\tM\tWestern\tcolon\nSRR010_control2\tcontrol\t44\t22.7\tF\tMediterranean\tcolon\nSRR011_control3\tcontrol\t31\t24.5\tM\tWestern\tcolon\nSRR012_control4\tcontrol\t48\t23.3\tF\tMediterranean\tcolon\n'
mits='sample-id\tgroup\tsoil_type\tph\tmoisture_pct\tsite\n#q2:types\tcategorical\tcategorical\tnumeric\tnumeric\tcategorical\nITS001_healthy1\thealthy\tclay\t6.8\t42.0\tField_A\nITS002_healthy2\thealthy\tsandy_loam\t6.5\t38.0\tField_A\nITS003_diseased1\tdiseased\tclay\t5.9\t51.0\tField_B\nITS004_diseased2\tdiseased\tclay\t5.7\t55.0\tField_B\nITS005_control1\tcontrol\tsandy_loam\t6.6\t40.0\tField_C\nITS006_control2\tcontrol\tclay\t6.7\t41.0\tField_C\nITS007_control3\tcontrol\tsandy_loam\t6.4\t39.0\tField_C\nITS008_control4\tcontrol\tclay\t6.9\t43.0\tField_C\n'
with open(B+'/metadata_16S.tsv','w') as f: f.write(m16)
with open(B+'/metadata_ITS.tsv','w') as f: f.write(mits)
mf=['sample-id\tforward-absolute-filepath\treverse-absolute-filepath']+[f'{s}\t{D16}/{s}_S{i}_L001_R1_001.fastq.gz\t{D16}/{s}_S{i}_L001_R2_001.fastq.gz' for i,s in enumerate(S16,1)]
with open(B+'/manifest_16S.tsv','w') as f: f.write('\n'.join(mf)+'\n')
print('ALL DONE')
